// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfL8sRGjZUoMWE0T6fxMy1ZBHgvVQXh4E',
    appId: '1:760422703045:web:95edb3cc59fd81fabcb5ac',
    messagingSenderId: '760422703045',
    projectId: 'my-demo-chat-a30aa',
    authDomain: 'my-demo-chat-a30aa.firebaseapp.com',
    storageBucket: 'my-demo-chat-a30aa.firebasestorage.app',
    measurementId: 'G-5ME3KX54C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPabp-wHvLBCp63BBfyiJk2LBqVsM-ly4',
    appId: '1:760422703045:android:849b13c7978e1f5abcb5ac',
    messagingSenderId: '760422703045',
    projectId: 'my-demo-chat-a30aa',
    storageBucket: 'my-demo-chat-a30aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACmJqb7FMvFMKKa8pBoQVAAy_c4OWYHDM',
    appId: '1:760422703045:ios:29297c8efb7140aebcb5ac',
    messagingSenderId: '760422703045',
    projectId: 'my-demo-chat-a30aa',
    storageBucket: 'my-demo-chat-a30aa.firebasestorage.app',
    androidClientId: '760422703045-4pecbfflb15mlqduqtlbshv171gldqmb.apps.googleusercontent.com',
    iosClientId: '760422703045-5p4u3u7trpj7rkpr66614n3ienotkgij.apps.googleusercontent.com',
    iosBundleId: 'com.example.logindemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACmJqb7FMvFMKKa8pBoQVAAy_c4OWYHDM',
    appId: '1:760422703045:ios:29297c8efb7140aebcb5ac',
    messagingSenderId: '760422703045',
    projectId: 'my-demo-chat-a30aa',
    storageBucket: 'my-demo-chat-a30aa.firebasestorage.app',
    androidClientId: '760422703045-4pecbfflb15mlqduqtlbshv171gldqmb.apps.googleusercontent.com',
    iosClientId: '760422703045-5p4u3u7trpj7rkpr66614n3ienotkgij.apps.googleusercontent.com',
    iosBundleId: 'com.example.logindemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfL8sRGjZUoMWE0T6fxMy1ZBHgvVQXh4E',
    appId: '1:760422703045:web:6e38ad70fcf54e1abcb5ac',
    messagingSenderId: '760422703045',
    projectId: 'my-demo-chat-a30aa',
    authDomain: 'my-demo-chat-a30aa.firebaseapp.com',
    storageBucket: 'my-demo-chat-a30aa.firebasestorage.app',
    measurementId: 'G-JDSZ5TWJ18',
  );
}
